version: '3.6'

services:
  backend:
    build: .
    ports:
      - 5000:5000

  db:
    image: neo4j
    ports: 
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/tpPass