version: '3.6'

services:
  backend:
    image: travelplannerapp/backend
    ports:
      - 5000:80

  db:
    image: neo4j
    ports: 
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - /home/travelPlanner/db/data:/data
      - /home/travelPlanner/db/logs:/logs
      - /home/travelPlanner/db/import:/import
      - /home/travelPlanner/db/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/tpPass 