FROM mcr.microsoft.com/dotnet/core/sdk as build

WORKDIR /build
COPY . . 
RUN dotnet publish -c Release TravelPlanner.App

FROM mcr.microsoft.com/dotnet/core/aspnet

WORKDIR /app

COPY --from=build /build/TravelPlanner.App/bin/Release/netcoreapp3.1/publish ./bin
COPY --from=build /build/TravelPlanner.App/obj/Release/netcoreapp3.1 ./obj

WORKDIR /app/bin

ENTRYPOINT dotnet TravelPlanner.App.dll