# This is a basic workflow to help you get started with Actions

name: Publish Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - uses: actions/checkout@v1   
          - name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          - name: Build the Docker image
            run: docker build ./Backend --file ./Backend/Dockerfile.Release --tag travelplannerapp/backend
          - name: Push the tagged Docker image
            run: docker push travelplannerapp/backend
           
